# Generated by Django 3.0 on 2021-06-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
                ('languages', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('enquirydate', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('enquiry', 'enquiry'), ('joined', 'joined')], default='enquiry', max_length=20)),
                ('cources', models.ManyToManyField(to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FeePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('fdate', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(to='home.Trainer'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('batchstatus', models.CharField(choices=[('new', 'new'), ('running', 'running'), ('finished', 'finished')], default='new', max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('students', models.ManyToManyField(to='home.Student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Trainer')),
            ],
        ),
    ]
